// File generated by FlutterFire CLI.
// Run: dart pub global activate flutterfire_cli && flutterfire configure
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('DuelDots does not support web.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Replace these with your Firebase project values via `flutterfire configure`

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACcNrzTbDeT3TMuskikw1g40j-MkLwTiQ',
    appId: '1:372248108528:android:0bbb7ce7be18fcba01d135',
    messagingSenderId: '372248108528',
    projectId: 'dueldots-3f969',
    storageBucket: 'dueldots-3f969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD30YkieY7iJEUE8uAZpG_j37WyDUdwH0g',
    appId: '1:372248108528:ios:4137cfd3b7ee50ba01d135',
    messagingSenderId: '372248108528',
    projectId: 'dueldots-3f969',
    storageBucket: 'dueldots-3f969.firebasestorage.app',
    iosBundleId: 'com.dueldots.duelDots',
  );
}
